// DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** References another document, used as a foreign key */
  Reference: any;
  JSON: any;
  JSONObject: any;
};

export type Node = {
  id: Scalars['ID'];
};

export type Document = {
  sys?: Maybe<SystemInfo>;
  id: Scalars['ID'];
};

export type FormField = {
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};




export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename?: Maybe<Scalars['String']>;
  basename?: Maybe<Scalars['String']>;
  breadcrumbs?: Maybe<Array<Maybe<Scalars['String']>>>;
  path?: Maybe<Scalars['String']>;
  relativePath?: Maybe<Scalars['String']>;
  extension?: Maybe<Scalars['String']>;
  template?: Maybe<Scalars['String']>;
  collection?: Maybe<Section>;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: Maybe<Scalars['Boolean']>;
};

export type Section = {
  __typename?: 'Section';
  type?: Maybe<Scalars['String']>;
  path?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  create?: Maybe<Scalars['String']>;
  match?: Maybe<Scalars['String']>;
  new_doc_ext?: Maybe<Scalars['String']>;
  templates?: Maybe<Array<Maybe<Scalars['String']>>>;
  slug?: Maybe<Scalars['String']>;
  documents?: Maybe<Array<Maybe<Document>>>;
};

export type SectionDocumentUnion = Games_Document | Years_Document;

export type SectionParams = {
  games?: Maybe<Games_Input>;
  years?: Maybe<Years_Input>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument?: Maybe<Document>;
  updateDocument?: Maybe<SectionDocumentUnion>;
  updateGamesDocument?: Maybe<Games_Document>;
  updateYearsDocument?: Maybe<Years_Document>;
};


export type MutationAddPendingDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  collection?: Maybe<Scalars['String']>;
  template?: Maybe<Scalars['String']>;
};


export type MutationUpdateDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<SectionParams>;
};


export type MutationUpdateGamesDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<Games_Input>;
};


export type MutationUpdateYearsDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<Years_Input>;
};

export type Query = {
  __typename?: 'Query';
  node?: Maybe<Node>;
  getDocument?: Maybe<SectionDocumentUnion>;
  getCollections?: Maybe<Array<Maybe<Section>>>;
  getCollection?: Maybe<Section>;
  getGamesDocument?: Maybe<Games_Document>;
  getGamesList?: Maybe<Array<Maybe<Games_Document>>>;
  getYearsDocument?: Maybe<Years_Document>;
  getYearsList?: Maybe<Array<Maybe<Years_Document>>>;
};


export type QueryNodeArgs = {
  id: Scalars['ID'];
};


export type QueryGetDocumentArgs = {
  collection?: Maybe<Scalars['String']>;
  relativePath?: Maybe<Scalars['String']>;
};


export type QueryGetCollectionArgs = {
  collection?: Maybe<Scalars['String']>;
};


export type QueryGetGamesDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
};


export type QueryGetYearsDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
};

export type Games_Data = Game_Doc_Data;

export type Games_Input = {
  game?: Maybe<Game_Doc_Input>;
};

export type Games_Values = Game_Doc_Values;

export type Games_Form = Game_Doc_Form;

export type Games_Document = Node & Document & {
  __typename?: 'Games_Document';
  id: Scalars['ID'];
  sys?: Maybe<SystemInfo>;
  data?: Maybe<Games_Data>;
  values?: Maybe<Games_Values>;
  form?: Maybe<Games_Form>;
};

export type Physical_Data = {
  __typename?: 'Physical_Data';
  console?: Maybe<Scalars['String']>;
};

export type Digital_Data = {
  __typename?: 'Digital_Data';
  store?: Maybe<Scalars['String']>;
};

export type Game_Variants_Data = Physical_Data | Digital_Data;

export type Game_Doc_Data = {
  __typename?: 'Game_Doc_Data';
  title?: Maybe<Scalars['String']>;
  deck?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
  wiki?: Maybe<Scalars['String']>;
  variants?: Maybe<Array<Maybe<Game_Variants_Data>>>;
  thoughts?: Maybe<Scalars['String']>;
  review?: Maybe<Scalars['String']>;
  invested?: Maybe<Scalars['String']>;
  _body?: Maybe<Scalars['String']>;
};

export type Physical_Values = {
  __typename?: 'Physical_Values';
  console?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type Digital_Values = {
  __typename?: 'Digital_Values';
  store?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type Game_Variants_Values = Physical_Values | Digital_Values;

export type Game_Doc_Values = {
  __typename?: 'Game_Doc_Values';
  title?: Maybe<Scalars['String']>;
  deck?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
  wiki?: Maybe<Scalars['String']>;
  variants?: Maybe<Array<Maybe<Game_Variants_Values>>>;
  thoughts?: Maybe<Scalars['String']>;
  review?: Maybe<Scalars['Reference']>;
  invested?: Maybe<Scalars['String']>;
  _body?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type TextField = FormField & {
  __typename?: 'TextField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type TextareaField = FormField & {
  __typename?: 'TextareaField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type Physical_FormFieldsUnion = TextField;

export type Physical_Form = {
  __typename?: 'Physical_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Physical_FormFieldsUnion>>>;
};

export type Digital_FormFieldsUnion = TextField;

export type Digital_Form = {
  __typename?: 'Digital_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Digital_FormFieldsUnion>>>;
};

export type Game_Variants_BlocksFieldTemplates = {
  __typename?: 'Game_Variants_BlocksFieldTemplates';
  physical?: Maybe<Physical_Form>;
  digital?: Maybe<Digital_Form>;
};

export type Game_Variants_BlocksField = FormField & {
  __typename?: 'Game_Variants_BlocksField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  templates?: Maybe<Game_Variants_BlocksFieldTemplates>;
};

export type SelectField = FormField & {
  __typename?: 'SelectField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  options?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type Game_Doc_FormFieldsUnion = TextField | TextareaField | Game_Variants_BlocksField | SelectField;

export type Game_Doc_Form = {
  __typename?: 'Game_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Game_Doc_FormFieldsUnion>>>;
};

export type Physical_Input = {
  console?: Maybe<Scalars['String']>;
};

export type Digital_Input = {
  store?: Maybe<Scalars['String']>;
};

export type Variants_Input = {
  physical?: Maybe<Physical_Input>;
  digital?: Maybe<Digital_Input>;
};

export type Game_Doc_Input = {
  title?: Maybe<Scalars['String']>;
  deck?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
  wiki?: Maybe<Scalars['String']>;
  variants?: Maybe<Array<Maybe<Variants_Input>>>;
  thoughts?: Maybe<Scalars['String']>;
  review?: Maybe<Scalars['String']>;
  invested?: Maybe<Scalars['String']>;
  _body?: Maybe<Scalars['String']>;
};

export type Years_Data = Year_Doc_Data;

export type Years_Input = {
  year?: Maybe<Year_Doc_Input>;
};

export type Years_Values = Year_Doc_Values;

export type Years_Form = Year_Doc_Form;

export type Years_Document = Node & Document & {
  __typename?: 'Years_Document';
  id: Scalars['ID'];
  sys?: Maybe<SystemInfo>;
  data?: Maybe<Years_Data>;
  values?: Maybe<Years_Values>;
  form?: Maybe<Years_Form>;
};

export type Year_Doc_Data = {
  __typename?: 'Year_Doc_Data';
  title?: Maybe<Scalars['String']>;
  deck?: Maybe<Scalars['String']>;
  games?: Maybe<Array<Maybe<Games_Document>>>;
  _body?: Maybe<Scalars['String']>;
};

export type Year_Doc_Values = {
  __typename?: 'Year_Doc_Values';
  title?: Maybe<Scalars['String']>;
  deck?: Maybe<Scalars['String']>;
  games?: Maybe<Array<Maybe<Scalars['String']>>>;
  _body?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type List_FormFieldsUnion = TextField | SelectField;

export type ListField = FormField & {
  __typename?: 'ListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  defaultItem?: Maybe<Scalars['String']>;
  field?: Maybe<List_FormFieldsUnion>;
};

export type Year_Doc_FormFieldsUnion = TextField | TextareaField | ListField;

export type Year_Doc_Form = {
  __typename?: 'Year_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Year_Doc_FormFieldsUnion>>>;
};

export type Year_Doc_Input = {
  title?: Maybe<Scalars['String']>;
  deck?: Maybe<Scalars['String']>;
  games?: Maybe<Array<Maybe<Scalars['String']>>>;
  _body?: Maybe<Scalars['String']>;
};

